### ISSUE TITLE
List of different datatypes cannot be saved

### ISSUE THREAD

**Issue by pheuer** [varchasgopalaswamy/prepper#1]
A class with the following list attribute

`[1, 'two', 3.3]` 

Raises an exception
`ValueError: Group /test_var is an object of type <class 'list'> that does not support being saved to an HDF5 file!`

While a list of the same type does not, e.g. 

`[1,2,3]`

**Comment by varchasgopalaswamy** [comment]
Interesting. That's definitely a bug; there's no reason why heterogeneous lists shouldn't be saveable. I'll take a look; most of my use cases were homogeneous lists so that's probably why I didn't notice

**Comment by varchasgopalaswamy** [comment]
What should happen is that it should try to trigger https://github.com/varchasgopalaswamy/prepper/blob/main/prepper/io_handlers.py#L292, fail to do that because the list is heterogeneous, and then go to https://github.com/varchasgopalaswamy/prepper/blob/main/prepper/io_handlers.py#L435

**Comment by varchasgopalaswamy** [comment]
@pheuer I added a check to make sure that the list was homogenous before passing it to the HDF5 dataset writer. Heterogenous lists of native python dtypes fail this check and therefore end up being processed by the sequence writer. See 478201e
